"""Renders a stored report as an .xlsx workbook.

Layout is one Summary sheet from the report's frozen figures, then a sheet per
detail table. Anyone opening this in Excel should be able to sort and filter it
without unpicking a layout, so each sheet is a plain header row plus data, with
a freeze pane and an autofilter — no merged cells, no blank spacer rows.
"""

import io
from datetime import date, datetime

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

HEADER_FILL = PatternFill("solid", fgColor="1F2937")
HEADER_FONT = Font(color="FFFFFF", bold=True)
TITLE_FONT = Font(bold=True, size=14)
SECTION_FONT = Font(bold=True)
DATE_FORMAT = "yyyy-mm-dd hh:mm:ss"

# Excel refuses sheet names over 31 chars or containing : \ / ? * [ ]
_ILLEGAL_SHEET_CHARS = set(r':\/?*[]')


def _safe_sheet_name(name: str) -> str:
    cleaned = "".join("-" if c in _ILLEGAL_SHEET_CHARS else c for c in name)
    return cleaned[:31] or "Sheet"


def _cell(value):
    """Coerces a value into something Excel stores natively where it can.

    Dicts and lists only reach here from JSON summary fields; they are written
    as text rather than dropped, so nothing in the report goes missing.
    """
    if isinstance(value, (datetime, date, int, float, str, bool)) or value is None:
        return value
    return str(value)


def _add_sheet(wb: Workbook, title: str, rows: list[dict]) -> None:
    ws = wb.create_sheet(_safe_sheet_name(title))
    if not rows:
        ws.append([f"No {title.lower()} in this report's window."])
        return

    # Every row in a detail table is built from the same dict literal, so the
    # first row's keys are the full column set.
    columns = list(rows[0].keys())
    ws.append(columns)
    for row in rows:
        ws.append([_cell(row.get(c)) for c in columns])

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(columns))}{len(rows) + 1}"
    for i, name in enumerate(columns, start=1):
        width = max(len(str(name)) + 2, 12)
        if name in ("Title", "Alert ID", "Device", "Attack family"):
            width = max(width, 24)
        ws.column_dimensions[get_column_letter(i)].width = min(width, 48)


def _summary_rows(report) -> list[list]:
    """The Summary sheet, as (label, value) pairs with section headings."""
    s = report.summary_stats or {}
    scope = s.get("scope") or {}
    rows: list[list] = [
        [report.title or f"Report #{report.id}"],
        [],
        ["Report type", report.report_type],
        ["Period start", report.period_start],
        ["Period end", report.period_end],
        ["Generated at", report.created_at],
        ["Generated by", report.author.username if report.author else None],
    ]

    if "patient" in scope:
        p = scope["patient"]
        rows += [
            [],
            ["Patient"],
            ["Patient code", p.get("patient_code")],
            ["Age band", p.get("age_band")],
            ["Sex", p.get("sex")],
            ["Ward", p.get("ward")],
            ["Admitted", p.get("admitted_at")],
            ["Discharged", p.get("discharged_at") or "still admitted"],
            ["Devices in window", len(p.get("devices") or [])],
        ]
        for d in p.get("devices") or []:
            label = f"  {d['device_uid']}"
            detail = d.get("type") or "unknown type"
            if d.get("life_critical"):
                detail += " (life-critical)"
            rows.append([label, detail])
    elif "device" in scope:
        d = scope["device"]
        rows += [
            [],
            ["Device"],
            ["Device ID", d.get("device_uid")],
            ["Type", d.get("type")],
            ["Ward", d.get("ward")],
            ["Status", d.get("status")],
        ]
    elif "ward" in scope:
        w = scope["ward"]
        rows += [[], ["Ward"], ["Name", w.get("name")],
                 ["Criticality", w.get("criticality")], ["Devices", w.get("devices")]]

    filters = {k: v for k, v in (report.filters or {}).items()}
    if filters:
        rows += [[], ["Filters applied"]]
        rows += [[f"  {k}", _cell(v)] for k, v in filters.items()]

    rows += [
        [],
        ["Detection totals"],
        ["Detections", s.get("total_detections", 0)],
        ["Flagged share", s.get("flagged_share", 0)],
        ["Average inference latency (ms)", s.get("avg_inference_latency_ms")],
    ]
    for verdict, count in (s.get("detections_by_verdict") or {}).items():
        rows.append([f"  {verdict.replace('_', ' ')}", count])

    rows += [[], ["Alerts"], ["Total alerts", s.get("total_alerts", 0)]]
    for severity, count in (s.get("alerts_by_severity") or {}).items():
        rows.append([f"  severity: {severity}", count])
    for st, count in (s.get("alerts_by_status") or {}).items():
        rows.append([f"  status: {st}", count])
    for fam in s.get("top_attack_families") or []:
        rows.append([f"  family: {fam['family']}", fam["alerts"]])

    rows += [
        [],
        ["Vitals (Stage 4)"],
        ["Readings", s.get("vitals_readings", 0)],
        ["Scored by Stage 4", s.get("vitals_scored_by_stage4", 0)],
        ["Implausible", s.get("vitals_implausible", 0)],
    ]

    if s.get("busiest_devices"):
        rows += [[], ["Busiest devices"]]
        rows += [[f"  {d['device_uid']}", d["detections"]] for d in s["busiest_devices"]]

    rows += [
        [],
        ["The figures above are the frozen snapshot taken when this report was generated."],
        ["The detail sheets are re-read at export time, so an alert's status may have moved on since."],
    ]
    return rows


def build_workbook(report, details: dict[str, list[dict]]) -> bytes:
    wb = Workbook()
    summary = wb.active
    summary.title = "Summary"

    for row in _summary_rows(report):
        summary.append([_cell(v) for v in row])

    # Section headings are the rows with a label and no value; the title is row 1.
    summary["A1"].font = TITLE_FONT
    for r in range(2, summary.max_row + 1):
        label, value = summary.cell(r, 1), summary.cell(r, 2)
        if label.value and value.value is None and not str(label.value).startswith(" "):
            label.font = SECTION_FONT
        if isinstance(value.value, (datetime, date)):
            value.number_format = DATE_FORMAT
        if isinstance(label.value, (datetime, date)):
            label.number_format = DATE_FORMAT
    summary.column_dimensions["A"].width = 38
    summary.column_dimensions["B"].width = 44
    summary["B1"].alignment = Alignment(wrap_text=True)

    for title, rows in details.items():
        _add_sheet(wb, title, rows)

    # Style the header row of each detail sheet and format its date columns.
    for ws in wb.worksheets[1:]:
        if ws.max_row < 2:
            continue
        for cell in ws[1]:
            cell.fill = HEADER_FILL
            cell.font = HEADER_FONT
        for col in range(1, ws.max_column + 1):
            if isinstance(ws.cell(2, col).value, (datetime, date)):
                letter = get_column_letter(col)
                ws.column_dimensions[letter].width = 21
                for r in range(2, ws.max_row + 1):
                    ws.cell(r, col).number_format = DATE_FORMAT

    stream = io.BytesIO()
    wb.save(stream)
    return stream.getvalue()


def filename_for(report) -> str:
    """A filename that sorts and reads sensibly in a downloads folder."""
    stamp = (report.created_at or datetime.utcnow()).strftime("%Y%m%d")
    scope = (report.summary_stats or {}).get("scope") or {}
    if "patient" in scope:
        subject = scope["patient"]["patient_code"]
    elif "device" in scope:
        subject = scope["device"]["device_uid"]
    elif "ward" in scope:
        subject = scope["ward"]["name"]
    else:
        subject = report.report_type
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in str(subject))
    return f"iomt-report-{safe}-{stamp}-{report.id}.xlsx"
